version: "3"
services:
  postgresql:
    image: postgres:13.10
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  mailcatcher:
    image: dockage/mailcatcher:0.8.2
    ports:
      - "127.0.0.1:1080:1080"
      - "127.0.0.1:1025:1025"

  rails:
    build:
      context: ./
      dockerfile: development.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgresql
      - redis
    volumes:
      - ./:/app

volumes:
  dbdata: