default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: "postgresql://postgres:password@postgresql/docker_compose_example"

test:
  <<: *default
  url: "postgresql://postgres:password@postgresql/docker_compose_example_test"

production:
  <<: *default